name: tests

on:
  pull_request:
      types: [ opened, synchronize, reopened, ready_for_review, labeled, unlabeled ]
  push:
    branches: [ master ]

jobs:

  test-on-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository 
        uses: actions/checkout@v2
      - name: Build
        run: |
          dotnet build ./BobClient/
      - name: Test net50
        run: |
          dotnet test ./BobClient/ --no-build -f "net5.0"


  test-on-windows:
    runs-on: windows-latest
    steps:
      - name: Checks-out repository 
        uses: actions/checkout@v2
      - name: Build
        run: |
          dotnet build ./BobClient/
      - name: Test net462
        run: |
          dotnet test ./BobClient/ --no-build -f "net462" --blame-hang --blame-hang-timeout 15m -l "console;verbosity=detailed"
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            ./BobClient/Qoollo.BobClient.UnitTests/TestResults
            ./BobClient/Qoollo.BobClient.UnitTests/bin/Debug/net462/Test_trace.log
            ./BobClient/Qoollo.BobClient.UnitTests/bin/Debug/net462/Test_hang.log